<?xml version="1.0" encoding="utf-8"?><Database Name="smarthome" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN-RGNVB6V4INV;Initial Catalog=smarthome;Integrated Security=False;Persist Security Info=True;User ID=u_smarthome" SettingsObjectName="UniversalServer.Properties.Settings" SettingsPropertyName="smarthomeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.wetterwerte" Member="wetterwerte">
    <Type Name="wetterwerte">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="temperatur" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="humidity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="druck" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sender_ip" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>